server:
  port: 10010
spring:
  application:
    name: gateway
  profiles:
    active: dev
ignore:
  auth:
    whites-url:
      - /admin/sys/**
      - /**/doc.html                    # 文档页面
      - /**/v3/api-docs/**              # OpenAPI 3 文档数据
      - /**/swagger-resources/**        # Swagger 资源
      - /**/webjars/**                  # 前端静态资源
      - /**/favicon.ico                 # 网站图标
      - /**/swagger-ui.html             # Swagger UI (如果使用)
      - /**/swagger-ui/**
knife4j:
  enable-aggregation: true
  cloud:
    enable: true
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
      namespace: c4a1ae5e-f5c4-4bb7-9f91-5bbfb2bfd764
  aggregation:
    - name: sys-server
      service-name: sys-server
      url: /admin/sys/v3/api-docs
      order: 1
      group-name: 系统管理服务