package com.jimeng.dataserver.ai.connector.service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.jimeng.persistence.entity.ConnectorSchema;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * 命名规则的「同形夹具」：本地两个真实系统的结构快照，按固定词表换了名字（设计文档 v3 §12）。
 *
 * <p>只保留规则会看的列（去掉 {@code _} 后以 {@code id} 结尾的列），列的顺序、表的唯一键原样保留。换名词表保证了
 * 「谁是谁的后缀」这层关系不变：换名前后跑同一条规则，两个系统分别是 33 条和 16 条，一一对应（2026-10-01 核过）。
 * 不含任何真实客户的表名。
 *
 * <p>每行是 {@code 表名|唯一键|列 列 列...}；唯一键写单列主键的列名，{@code -} 表示这张表确实没有唯一键；
 * 以 {@code + } 开头的行接着上一张表的列。
 */
final class RelationRuleFixtures {

    private static final ObjectMapper MAPPER = new ObjectMapper();

    /** 形同 klny_erp：19 张表。 */
    static final String ERP_A = """
            MD_BUYER|OID|OID SOID POID VERID DVERID PARENTID SUPPLIERID CLIENTID ADDRESSCOUNTRYID REGIONID
            + BUYERSUBJECTGROUPID MM_PARTNERSCHEMASID TRADEPARTNERID INTERNALORGUNITID CURRENCYID
            MD_COSTPOOL|OID|OID SOID POID VERID DVERID PARENTID CLIENTID CONTROLLINGAREAID COSTPOOLGROUPID SEGMENTID
            + RESPONSIBLEUSERID
            MD_ORGUNIT|OID|OID SOID POID VERID DVERID PARENTID LANGUAGEID COUNTRYID FIELDSTATUSVARIANTID CLIENTID
            + CURRENCYID REGIONID TIMEZONEID CREDITCONTROLAREAID FUNDMANAGEAREAID BUSINESSAREAID SUBJECTCHARTID
            + COUNTRYSUBJECTCHARTID COMPANYID PERIODTYPEID POSTPERIODTYPEID INDUSTRYID DERIVATIVERULEID ORGSTRUCTUREID
            MD_SUBJECT|OID|OID SOID POID VERID DVERID PARENTID SUBJECTGROUPID SUBJECTCHARTID GROUPSUBJECTID CLIENTID
            + FUNCTIONAREAID TRADEPARTNERID
            MD_SUPPLIER|OID|OID SOID POID VERID DVERID PARENTID COUNTRYID BUYERID CLIENTID REGIONID
            + SUPPLIERSUBJECTGROUPID PLANTID TRADEPARTNERID INTERNALORGUNITID
            QF_BUYER_ORGSETDTL|OID|OID SOID POID VERID DVERID ORGUNITID RECONSUBJECTID ASSIGNMENTRULEID
            + VCTOLERANCEGROUPID TERMOFPAYMENTID CREDITTERMOFPAYMENTID
            QF_EXT_IF17|OID|OID SOID POID VERID DVERID CONTRACTID TRANSID SYSID FRAMEWORKID DEPTID OURSIGNERID
            + UNDERTAKEID INNERCONTRACTID GENERALCONTRACTID UNDERTAKEDEPTUNITID
            QF_JOURNALDTL|OID|OID SOID POID VERID DVERID ENTRYBILLDTLID POSTINGKEYID NEWORGUNITID GLSUBJECTID BUYERID
            + SUPPLIERID ASSETID MATERIALID SPECIALGLID TRANSACTIONTYPEID CONSOLIDATIONTYPEID SUBJECTID ITEMCATEGORYID
            + COUNTRYSUBJECTID ITEMCURRENCYID ITEMFIRSTLOCALCURRENCYID ITEMSECONDLOCALCURRENCYID
            + ITEMTHIRDLOCALCURRENCYID TAXCODEID TAXSRCBILLDTLID CONTROLLINGAREAID COSTELEMENTID BUSINESSAREAID
            + PARTNERBUSINESSAREAID COSTCENTERID ORDERID COSTOBJECTID COSTPOOLID PARTNERCOSTPOOLID SEGMENTID
            + PARTNERSEGMENTID TASKNODEID ASSETSBUSINESSCLASSID SALESORDERID SALESORDERPLANDTLOID FUNCTIONALAREAID
            + PARTNERFUNCTIONALAREAID PLANTID BASEUNITID PURCHASINGID CREDITCONTROLAREAID UPDATECURRENCYID
            + CLEARINGJOURNALID CLEARINGJOURNALDTLID TERMOFPAYMENTID PAYMENTDICTIONARYID PAYMENTMETHODID
            + PAYMENTBLOCKREASONID PAYMENTCURRENRCYID REASONCODEID VALUESTRINGID CASHFLOWITEMID REFERENCEBILLID
            + REFERENCEBILLDTLID TRANSACTIONKEYID SRCSOID SRCOID VALUATIONTYPEID NETWORKID ACTIVITYID
            + PAYMENTMETHODSUPPLEMENTID HOUSEBANKID HOUSESUBJECTID TRADEPARTNERID BANKCHECKRESULTID ITEMLEDGERID
            + BUYORDERUNITID RECONSUBJECTID CLAUSEUNITID NEWFUNDMANAGEAREAID FUNDCENTERID COMMITMENTITEMID DEPARTMENTID
            + CUSTOMAUXILIARY01ID CUSTOMAUXILIARY02ID CUSTOMAUXILIARY03ID CUSTOMAUXILIARY04ID CUSTOMAUXILIARY05ID
            + CUSTOMAUXILIARY06ID CUSTOMAUXILIARY07ID CUSTOMAUXILIARY08ID CUSTOMAUXILIARY09ID CUSTOMAUXILIARY10ID
            + CUSTOMAUXILIARY11ID CUSTOMAUXILIARY12ID CUSTOMAUXILIARY13ID CUSTOMAUXILIARY14ID CUSTOMAUXILIARY15ID
            + CUSTOMAUXILIARY16ID CUSTOMAUXILIARY17ID CUSTOMAUXILIARY18ID CUSTOMAUXILIARY19ID CUSTOMAUXILIARY20ID
            + CUSTOMAUXILIARY21ID CUSTOMAUXILIARY22ID CUSTOMAUXILIARY23ID CUSTOMAUXILIARY24ID CUSTOMAUXILIARY25ID
            + CUSTOMAUXILIARY26ID CUSTOMAUXILIARY27ID CUSTOMAUXILIARY28ID CUSTOMAUXILIARY29ID CUSTOMAUXILIARY30ID
            + ITEMCLIENTID ENTRYSUMID IDENTITYID PURCHASEJOURNALID RECONTRACTID REFLOWTYPEID
            QF_SOURCELINEDTL|OID|OID SOID POID VERID DVERID JOURNALDTLID CLIENTID
            QF_SUPPLIER_ORGSETDTL|OID|OID SOID POID VERID DVERID ORGUNITID RECONSUBJECTID ASSIGNMENTRULEID
            + VCTOLERANCEGROUPID TERMOFPAYMENTID SUPPLIERSPECIFICTOLERANCEID CREDITTERMOFPAYMENTID
            QG_OBJSTATE|OID|OID SOID POID VERID DVERID SYSTEMSTATUSID PRESYSTEMSTATUSID
            QM_BUYORDERCONFIRM|OID|OID SOID POID VERID DVERID CONFIRMATIONCATEGORYID INBOUNDDELIVERYDTLID
            + INBOUNDDELIVERYBILLID
            QM_BUYORDERDTL|OID|OID SOID POID VERID DVERID MATERIALID MATERIALGROUPID PLANTID STORAGELOCATIONID
            + TAXCODEID ACCTASSIGNMENTCATID ITEMCATEGORYID DELIVERYTYPEID BUYERID SALEORGANIZATIONID
            + DISTRIBUTIONCHANNELID DIVISIONID PRICEUNITID UNITID BASEUNITID PURCHASEINFORECORDID SRCSOID SRCOID
            + RESERVATIONID SRCCONTRACTBILLDTLID COSTCENTERID COSTPOOLID FI_SUBJECTID BUSINESSAREAID ASSETID
            + SRCREQUISITIONBILLID SRCREQUISITIONBILLDTLID SRCCONTRACTBILLID VALUATIONTYPEID SHIPPINGCONDITIONID
            + LOADINGGROUPID SHIPPINGPOINTID SETCONFIRMATIONCONTROLID PS_TASKNODEID PS_NETWORKID CHECKINGGROUPID
            + CONFIRMDTLID PP_REQUIREMENTTYPEID PS_ACTIVITYID SRCSELLORDERBILLID DELIVERYBUYERID CROSSCONFIGMATERIALID
            + MATERIALCONFIGPROFILEID DEFAULT_CATEGORYTYPEID STORAGEPOINTID ORGUNITID SRCSELLORDERBILLDTLID
            + QMCONTROLKEYID DEMANDSRCPLANORDERID SRCDEMAND_MRPELEMENTID SRCDEMAND_ORDERID SRCDEMAND_ORDERBILLDTLID
            + PURCHASEREQUISITIONID PURCHASINGNUMBERID AGREEMENTID SELLORDERITEMID OVERALLLIMITCURRENCYID
            + MM_DOCUMENTTYPESID PERIODINDICATOR4SHELFID SHIPMENTSTORAGELOCATIONID PURORGANIZATIONID SUPPLIERID
            + PURCHASINGGROUPID SUPPLYINGPLANTID CLIENTID FUNCTIONALAREAID REFPURORDEROID DCDXID DCCXID
            QM_BUYORDERHEAD|OID|OID SOID POID VERID DVERID CLIENTID PURORGANIZATIONID PURCHASINGGROUPID ORGUNITID
            + PARTNERSCHEMASID SUPPLIERID SUPPLYINGPLANTID PRICINGPROCEDUREID PAYMENTTERMID CURRENCYID
            + MM_DOCUMENTTYPESID CHECKINGRULEID COUNTRYID PAYMENTDICTIONARYID DRAWERID PARENTID ZDCCGDDID ZZK_DCCGDDID
            + INSTANCEID ZUNITID
            QP_VENTURE|OID|OID SOID POID VERID DVERID PARENTID CLIENTID ORGUNITID PLANTID LOCATIONID ZZ_VENTUREID
            + STANDARDVENTUREID VENTUREID SHIELDID
            QS_SELLORDERDTL|OID|OID SOID POID VERID DVERID MATERIALID SD_ITEMCATEGORIESID PLANTID CONDITIONTYPEID
            + REASONFORREJECTIONID TAXCLASSIFICATIONID COSTPOOLID PRICEUNITID UNITID BASEUNITID PP_REQUIREMENTTYPEID
            + SD_ITEMCATEGORYGROUPSID ITEMCATEGORYHIGHERLEVELITEMID SD_ITEMCATEGORYUSAGEID SRCSOID SRCOID
            + ITEMPARTNERSCHEMASID ORGUNITID SD_MATERIALGROUPSID ITEM_SD_PRIGROUPS4BUYERSID STORAGELOCATIONID
            + ITEM_SD_INCOTERMSID PAYMENTMETHODID CONDITIONCURRENCYID SRCSALECONTRACTBILLID SRCSALECONTRACTBILLDTLID
            + SRCSALESORDERBILLID SRCSALESORDERBILLDTLID SRCSALESINVOICEBILLID SRCSALESINVOICEBILLDTLID
            + COSTINGVARIANTID ACCTASSIGNMENTCATID SHIPPINGPOINTID LOADINGGROUPID VALUATIONTYPEID PS_TASKNODEID
            + BILLINGPLANTYPEID TPSPURREQUISITIONID TPSPURORDERID MATERIALCONFIGPROFILEID BOMBILLDTLID
            + CROSSCONFIGMATERIALID ROOTMATERIALSELLORDERBILLDTLID HIGHBOMBILLDTLID DEFAULT_CATEGORYTYPEID
            + STORAGEPOINTID ORDERBOMBILLID SD_SALESDOCUMENTTYPESID SALEAREAID SOLDTOPARTYID SHIPTOPARTYID
            + SD_SALEOFFICEID SD_SALEGROUPSID REBATEAGREEMENTID SALEORGANIZATIONID DISTRIBUTIONCHANNELID CLIENTID
            + PAYERID RECEIVEINVOICEID TRANSPORTMOVETYPEID EFFECTIVETASKNODEID INTEDATAID USERMEASUREMENTID PRICETYPEID
            QS_SELLORDERHEAD|OID|OID SOID POID VERID DVERID PARENTID CLIENTID DELIVERYBLOCKID SALEORGANIZATIONID
            + DISTRIBUTIONCHANNELID DIVISIONID SD_SALEOFFICEID SD_SALEGROUPSID SD_BUYERGROUPSID SD_SALESDOCUMENTTYPESID
            + SD_SALESORDERREASONSID CURRENCYID PRICINGPROCEDUREID SD_PRICEGROUPS4BUYERSID SOLDTOPARTYID SHIPTOPARTYID
            + FI_TERMOFPAYMENTID SD_INCOTERMSID SD_REASON4BLOCKINGBILLIINGID HEAD_ORGUNITID HEAD_TAXCLASSIFICATIONID
            + SUBJECTGROUPID PAYMENTMETHODID PERIODTYPEID BUSINESSAREAID COSTCENTERID PAYERID CREDITCONTROLAREAID
            + RISKCATEGORYID SD_DOCUMENTCREDITGROUPID CREDITREPRESENTATIVEGROUPID SD_BILLINGDOCUMENTTYPEID
            + SD_DELIVERYBILLINGTYPEID PARTNERSCHEMASID SHIPPINGCONDITIONID SUBSTITUTEPROCEDUREID SD_SHIPPINGTYPEID
            + IVBILLINGDOCUMENTTYPEID REBATEAGREEMENTID COUNTRYID EXCHANGERATETYPEID LOCALCURRENCYID TCODEID
            + RECEIVEINVOICEID HEADPS_TASKNODEID BUYERSUBJECTASGGROUPID RECEIVINGPARTYID ARRIVE_SOLDTOPARTYID
            + ARRIVE_SHIPTOPARTYID INSTANCEID DELIVERYPLANID CREDITSUBJECTID RECEIPTSUPPLIERID ZZH_CONTRACTID
            RPT_BAL_2026|-|F_UNITID
            RPT_SUM_2026|-|F_UNITID
            """;

    /** 形同 erp_real：8 张表。 */
    static final String ERP_B = """
            MD_COSTPOOL|OID|OID SOID POID VERID DVERID PARENTID CLIENTID CONTROLLINGAREAID COSTPOOLGROUPID SEGMENTID
            + RESPONSIBLEUSERID
            MD_ORGUNIT|OID|OID SOID POID VERID DVERID PARENTID LANGUAGEID COUNTRYID FIELDSTATUSVARIANTID CLIENTID
            + CURRENCYID REGIONID TIMEZONEID CREDITCONTROLAREAID FUNDMANAGEAREAID BUSINESSAREAID SUBJECTCHARTID
            + COUNTRYSUBJECTCHARTID COMPANYID PERIODTYPEID POSTPERIODTYPEID INDUSTRYID DERIVATIVERULEID ORGSTRUCTUREID
            MD_SUBJECT|OID|OID SOID POID VERID DVERID PARENTID SUBJECTGROUPID SUBJECTCHARTID GROUPSUBJECTID CLIENTID
            + FUNCTIONAREAID TRADEPARTNERID
            MD_SUPPLIER|OID|OID SOID POID VERID DVERID PARENTID COUNTRYID BUYERID CLIENTID REGIONID
            + SUPPLIERSUBJECTGROUPID PLANTID TRADEPARTNERID INTERNALORGUNITID
            QF_JOURNALDTL|OID|OID SOID POID VERID DVERID ENTRYBILLDTLID POSTINGKEYID NEWORGUNITID GLSUBJECTID BUYERID
            + SUPPLIERID ASSETID MATERIALID SPECIALGLID TRANSACTIONTYPEID CONSOLIDATIONTYPEID SUBJECTID ITEMCATEGORYID
            + COUNTRYSUBJECTID ITEMCURRENCYID ITEMFIRSTLOCALCURRENCYID ITEMSECONDLOCALCURRENCYID
            + ITEMTHIRDLOCALCURRENCYID TAXCODEID TAXSRCBILLDTLID CONTROLLINGAREAID COSTELEMENTID BUSINESSAREAID
            + PARTNERBUSINESSAREAID COSTCENTERID ORDERID COSTOBJECTID COSTPOOLID PARTNERCOSTPOOLID SEGMENTID
            + PARTNERSEGMENTID TASKNODEID ASSETSBUSINESSCLASSID SALESORDERID SALESORDERPLANDTLOID FUNCTIONALAREAID
            + PARTNERFUNCTIONALAREAID PLANTID BASEUNITID PURCHASINGID CREDITCONTROLAREAID UPDATECURRENCYID
            + CLEARINGJOURNALID CLEARINGJOURNALDTLID TERMOFPAYMENTID PAYMENTDICTIONARYID PAYMENTMETHODID
            + PAYMENTBLOCKREASONID PAYMENTCURRENRCYID REASONCODEID VALUESTRINGID CASHFLOWITEMID REFERENCEBILLID
            + REFERENCEBILLDTLID TRANSACTIONKEYID SRCSOID SRCOID VALUATIONTYPEID NETWORKID ACTIVITYID
            + PAYMENTMETHODSUPPLEMENTID HOUSEBANKID HOUSESUBJECTID TRADEPARTNERID BANKCHECKRESULTID ITEMLEDGERID
            + BUYORDERUNITID RECONSUBJECTID CLAUSEUNITID NEWFUNDMANAGEAREAID FUNDCENTERID COMMITMENTITEMID DEPARTMENTID
            + CUSTOMAUXILIARY01ID CUSTOMAUXILIARY02ID CUSTOMAUXILIARY03ID CUSTOMAUXILIARY04ID CUSTOMAUXILIARY05ID
            + CUSTOMAUXILIARY06ID CUSTOMAUXILIARY07ID CUSTOMAUXILIARY08ID CUSTOMAUXILIARY09ID CUSTOMAUXILIARY10ID
            + CUSTOMAUXILIARY11ID CUSTOMAUXILIARY12ID CUSTOMAUXILIARY13ID CUSTOMAUXILIARY14ID CUSTOMAUXILIARY15ID
            + CUSTOMAUXILIARY16ID CUSTOMAUXILIARY17ID CUSTOMAUXILIARY18ID CUSTOMAUXILIARY19ID CUSTOMAUXILIARY20ID
            + CUSTOMAUXILIARY21ID CUSTOMAUXILIARY22ID CUSTOMAUXILIARY23ID CUSTOMAUXILIARY24ID CUSTOMAUXILIARY25ID
            + CUSTOMAUXILIARY26ID CUSTOMAUXILIARY27ID CUSTOMAUXILIARY28ID CUSTOMAUXILIARY29ID CUSTOMAUXILIARY30ID
            + ITEMCLIENTID ENTRYSUMID IDENTITYID PURCHASEJOURNALID RECONTRACTID REFLOWTYPEID
            QF_JOURNALDTL_EXT|OID|OID JOURNALTYPEID ORGUNITID CURRENCYID LEDGERGROUPID LEDGERID FIRSTLOCALCURRENCYID
            + SECONDLOCALCURRENCYID THIRDLOCALCURRENCYID FIRSTEXCHANGERATETYPEID SECONDEXCHANGERATETYPEID
            + THIRDEXCHANGERATETYPEID SUBJECTCHARTID COUNTRYSUBJECTCHARTID CLIENTID REVERSALREASONID REVERSALDOCUMENTID
            + COPIEDJOURNALID SRCORGUNITID CROSSORGSETJOURNALID HEADSRCSOID NUMBERRANGEID FUNDMANAGEAREAID JOURNALGUID
            + PARENTID LEDGERNUMBERRANGEID ATTACHID
            QF_SUPPLIER_ORGSETDTL|OID|OID SOID POID VERID DVERID ORGUNITID RECONSUBJECTID ASSIGNMENTRULEID
            + VCTOLERANCEGROUPID TERMOFPAYMENTID SUPPLIERSPECIFICTOLERANCEID CREDITTERMOFPAYMENTID
            QP_TASKNODE|OID|OID SOID POID VERID DVERID CLIENTID SHORTID ORGUNITID FUNCTIONALLOCATIONID VENTUREID
            + LOCATIONID USERFIELDKEYID PARENTID POSITIONID DEFINITIONID FIRSTDOWNID LEFTID RIGHTID WELL_ID OACODEID
            + PERFORMANCETYPEID
            """;

    /** {@link #ERP_A} 上命名规则应当推出的全部候选，按起点表、起点列排序。 */
    static final List<String> ERP_A_EXPECTED = List.of(
            "MD_BUYER.INTERNALORGUNITID -> MD_ORGUNIT.OID",
            "MD_BUYER.SUPPLIERID -> MD_SUPPLIER.OID",
            "MD_SUPPLIER.BUYERID -> MD_BUYER.OID",
            "MD_SUPPLIER.INTERNALORGUNITID -> MD_ORGUNIT.OID",
            "QF_BUYER_ORGSETDTL.ORGUNITID -> MD_ORGUNIT.OID",
            "QF_BUYER_ORGSETDTL.RECONSUBJECTID -> MD_SUBJECT.OID",
            "QF_JOURNALDTL.BUYERID -> MD_BUYER.OID",
            "QF_JOURNALDTL.COSTPOOLID -> MD_COSTPOOL.OID",
            "QF_JOURNALDTL.COUNTRYSUBJECTID -> MD_SUBJECT.OID",
            "QF_JOURNALDTL.GLSUBJECTID -> MD_SUBJECT.OID",
            "QF_JOURNALDTL.HOUSESUBJECTID -> MD_SUBJECT.OID",
            "QF_JOURNALDTL.NEWORGUNITID -> MD_ORGUNIT.OID",
            "QF_JOURNALDTL.PARTNERCOSTPOOLID -> MD_COSTPOOL.OID",
            "QF_JOURNALDTL.RECONSUBJECTID -> MD_SUBJECT.OID",
            "QF_JOURNALDTL.SUBJECTID -> MD_SUBJECT.OID",
            "QF_JOURNALDTL.SUPPLIERID -> MD_SUPPLIER.OID",
            "QF_SOURCELINEDTL.JOURNALDTLID -> QF_JOURNALDTL.OID",
            "QF_SUPPLIER_ORGSETDTL.ORGUNITID -> MD_ORGUNIT.OID",
            "QF_SUPPLIER_ORGSETDTL.RECONSUBJECTID -> MD_SUBJECT.OID",
            "QM_BUYORDERDTL.BUYERID -> MD_BUYER.OID",
            "QM_BUYORDERDTL.COSTPOOLID -> MD_COSTPOOL.OID",
            "QM_BUYORDERDTL.DELIVERYBUYERID -> MD_BUYER.OID",
            "QM_BUYORDERDTL.FI_SUBJECTID -> MD_SUBJECT.OID",
            "QM_BUYORDERDTL.ORGUNITID -> MD_ORGUNIT.OID",
            "QM_BUYORDERDTL.SUPPLIERID -> MD_SUPPLIER.OID",
            "QM_BUYORDERHEAD.ORGUNITID -> MD_ORGUNIT.OID",
            "QM_BUYORDERHEAD.SUPPLIERID -> MD_SUPPLIER.OID",
            "QP_VENTURE.ORGUNITID -> MD_ORGUNIT.OID",
            "QS_SELLORDERDTL.COSTPOOLID -> MD_COSTPOOL.OID",
            "QS_SELLORDERDTL.ORGUNITID -> MD_ORGUNIT.OID",
            "QS_SELLORDERHEAD.CREDITSUBJECTID -> MD_SUBJECT.OID",
            "QS_SELLORDERHEAD.HEAD_ORGUNITID -> MD_ORGUNIT.OID",
            "QS_SELLORDERHEAD.RECEIPTSUPPLIERID -> MD_SUPPLIER.OID");

    /** {@link #ERP_B} 上命名规则应当推出的全部候选。 */
    static final List<String> ERP_B_EXPECTED = List.of(
            "MD_SUPPLIER.INTERNALORGUNITID -> MD_ORGUNIT.OID",
            "QF_JOURNALDTL.COSTPOOLID -> MD_COSTPOOL.OID",
            "QF_JOURNALDTL.COUNTRYSUBJECTID -> MD_SUBJECT.OID",
            "QF_JOURNALDTL.GLSUBJECTID -> MD_SUBJECT.OID",
            "QF_JOURNALDTL.HOUSESUBJECTID -> MD_SUBJECT.OID",
            "QF_JOURNALDTL.NEWORGUNITID -> MD_ORGUNIT.OID",
            "QF_JOURNALDTL.PARTNERCOSTPOOLID -> MD_COSTPOOL.OID",
            "QF_JOURNALDTL.RECONSUBJECTID -> MD_SUBJECT.OID",
            "QF_JOURNALDTL.SUBJECTID -> MD_SUBJECT.OID",
            "QF_JOURNALDTL.SUPPLIERID -> MD_SUPPLIER.OID",
            "QF_JOURNALDTL.TASKNODEID -> QP_TASKNODE.OID",
            "QF_JOURNALDTL_EXT.ORGUNITID -> MD_ORGUNIT.OID",
            "QF_JOURNALDTL_EXT.SRCORGUNITID -> MD_ORGUNIT.OID",
            "QF_SUPPLIER_ORGSETDTL.ORGUNITID -> MD_ORGUNIT.OID",
            "QF_SUPPLIER_ORGSETDTL.RECONSUBJECTID -> MD_SUBJECT.OID",
            "QP_TASKNODE.ORGUNITID -> MD_ORGUNIT.OID");

    private RelationRuleFixtures() {
    }

    static List<ConnectorSchema> parse(String text) {
        Map<String, List<String>> columns = new LinkedHashMap<>();
        Map<String, String> keys = new LinkedHashMap<>();
        String current = null;
        for (String raw : text.strip().split("\n")) {
            String line = raw.strip();
            if (line.startsWith("+ ")) {
                columns.get(current).addAll(List.of(line.substring(2).trim().split(" ")));
                continue;
            }
            String[] parts = line.split("\\|", 3);
            current = parts[0];
            keys.put(current, parts[1]);
            columns.put(current, new ArrayList<>(List.of(parts[2].trim().split(" "))));
        }
        List<ConnectorSchema> out = new ArrayList<>();
        columns.forEach((table, cols) -> out.add(schema(table, keys.get(table), cols)));
        return out;
    }

    static ConnectorSchema schema(String table, String key, List<String> cols) {
        List<Map<String, Object>> fields = new ArrayList<>();
        for (String c : cols) {
            Map<String, Object> f = new LinkedHashMap<>();
            f.put("name", c);
            f.put("type", "decimal(19,0)");
            f.put("nullable", true);
            f.put("comment", "");
            fields.add(f);
        }
        Map<String, Object> detail = new LinkedHashMap<>();
        detail.put("name", table);
        detail.put("type", "TABLE");
        detail.put("fields", fields);
        detail.put("extra", Map.of("unique_keys", "-".equals(key) ? List.of()
                : List.of(Map.of("name", "PRIMARY", "primary", true, "columns", List.of(key)))));
        ConnectorSchema row = new ConnectorSchema();
        row.setConnectorId(1L);
        row.setObjectType("TABLE");
        row.setObjectName(table);
        row.setDetailJson(json(detail));
        return row;
    }

    private static String json(Object value) {
        try {
            return MAPPER.writeValueAsString(value);
        } catch (JsonProcessingException e) {
            throw new IllegalStateException(e);
        }
    }
}
